name: Bug report
description: Create a report when something isn't working
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: "## Information about the bug"
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behaviour
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Does the issue also occur with other 3rd-party launchers?
      description: |
        Many issues (e.g. with gesture navigation or the recent apps screen) are not caused by Niagara Launcher itself, but rather by the surrounding Android OS. 
        Testing with other launchers gives us a clue if the issue is caused by Niagara Launcher or not.
        Examples for popular 3rd-party launchers are (open using CTRL/⌘+Click): [Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher), [Microsoft Launcher](https://play.google.com/store/apps/details?id=com.microsoft.launcher) or [Smart Launcher](https://play.google.com/store/apps/details?id=ginlemon.flowerfree).
      multiple: false
      options:
        - "Problem occurs with other launchers"
        - "Problem doesn't occur with other launchers"
        - "Not applicable"
    validations:
      required: true
  - type: input
    attributes:
      label: Other 3rd-party launcher(s) tested
      description: Please list the name(s) of the other launcher(s) you've tested. (Leave blank if not applicable)
  - type: markdown
    attributes:
      value: "## Information about your device"
  - type: input
    attributes:
        label: Device name
        description: Manufacturer and model of your device
        placeholder: e.g. Google Pixel 5
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Android version
      description: "[Click here if you need help determining your Android version (open this using CTRL/⌘+Click)](https://support.google.com/android/answer/7680439)"
      options:
        - Android 5.0 (Lollipop)
        - Android 5.1 (Lollipop)
        - Android 6.0 (Marshmallow)
        - Android 7.0 (Nougat)
        - Android 7.1 (Nougat)
        - Android 8.0 (Oreo)
        - Android 8.1 (Oreo)
        - Android 9 (Pie)
        - Android 10
        - Android 11
        - Android 12
        - Android 13
    validations:
      required: true
  - type: markdown
    attributes:
      value: "---"
  - type: textarea
    attributes:
      label: Screenshots / Screen recordings
      description: If applicable, add screenshots or -recordings to help explain your problem. You can paste them here directly.
    validations:
      required: false
