name: Feature request
description: Suggest an idea

body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: e.g I'm always frustrated when [...]
  - type: markdown
    attributes:
      - value: |
          Please remember: a feature should be...
          *Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
          *Impactful* · Either appealing for many or necessary for some.
          *Universal* · Has to work everywhere: in every country, on all phones.
          *Independent* · Doesn’t add complexity if it’s not being used.
          _[Click here to read the full knowledge base article about Niagara's design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles)_
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true