name: Mark new issues for moderation
on:
  issues:
    types:
      - opened
jobs:
  label_issue:
    runs-on: ubuntu-latest
    name: Label issue
    steps:
      #      - name: Simple Issue Labeler
      #        uses: andymckay/labeler@1.0.4
      #        with:
      #          add-labels: "in-moderation"
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@0ee0e95e4cc4752546922ac94e72cc2294fb301b # tag=v1.8.0
        with:
          assignees: Oddward

